import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

const PollPage: NextPage = () => {
  const router = useRouter();
  const pollId = router.query.pollId as string;
  const pollRes = api.poll.getPoll.useQuery(
    {
      pollId,
    },
    {
      enabled: !!pollId,
    }
  );

  const poll = pollRes.data;

  console.log(poll);


  return (
    <>
      <Head>
        <title>Pick a pole to vote on</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="text-white container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {pollRes.isLoading ? <div>Loading...</div> : (
            <>
              <h1 className="text-4xl">
                {poll?.prompt}
              </h1>
              <form>
                {poll?.answers.map((answer) => {
                  const inputId = `answer-${answer.id}`;
                  return (
                    <fieldset key={answer.id} className="mb-6 text-lg">
                      <input type="radio" id={inputId} name="answer" value={answer.id} />
                      <label htmlFor={inputId}> {answer.text}</label>
                    </fieldset>
                  )
                })}
                <button type="submit" className="text-3xl" >Submit</button>
              </form>
            </>
          )}
        </div>
      </main>
    </>
  );
};

export default PollPage;
